### ISSUE TITLE
 ¿Hay alguna forma de pasarlo a una versión inferior a la 4.0?

### ISSUE THREAD

**Issue by Fr3dyx** [KyoSleep1/GonckoModels#1]
o tendria que reacer todo el codigo?, como no se que metodos trae la 4.0 (a aparte que la wiki no esta del todo completa) para arriba me preguntaba si hay una forma.

**Comment by KyoSleep1** [comment]
El código es muy distinto entre estas dos versiones; inicialmente este repositorio inició en la 3.0 pero fue movido a la 4.0 por la facilidad que otorga en muchos aspectos como el ItemLayerRenderer o el ArmorLayerRenderer. 

Sí, es posible pasarlo a una versión inferior siempre y cuando tengas los conocimientos necesarios, pero yo no recomiendo seguir usando una versión inferior de geckolib.
